<?php

return [
    'countries' => [
        'India' => [
            'currency' => 'INR',
            'symbol' => '₹',
            'states' => [
                'AN' => 'Andaman and Nicobar Islands',
                'AP' => 'Andhra Pradesh',
                'AR' => 'Arunachal Pradesh',
                'AS' => 'Assam',
                'BR' => 'Bihar',
                'CG' => 'Chhattisgarh',
                'CH' => 'Chandigarh',
                'DN' => 'Dadra and Nagar Haveli and Daman and Diu',
                'DL' => 'Delhi',
                'GA' => 'Goa',
                'GJ' => 'Gujarat',
                'HR' => 'Haryana',
                'HP' => 'Himachal Pradesh',
                'JK' => 'Jammu and Kashmir',
                'JH' => 'Jharkhand',
                'KA' => 'Karnataka',
                'KL' => 'Kerala',
                'LA' => 'Ladakh',
                'LD' => 'Lakshadweep',
                'MP' => 'Madhya Pradesh',
                'MH' => 'Maharashtra',
                'MN' => 'Manipur',
                'ML' => 'Meghalaya',
                'MZ' => 'Mizoram',
                'NL' => 'Nagaland',
                'OD' => 'Odisha',
                'PY' => 'Puducherry',
                'PB' => 'Punjab',
                'RJ' => 'Rajasthan',
                'SK' => 'Sikkim',
                'TG' => 'Telangana',
                'TN' => 'Tamil Nadu',
                'TR' => 'Tripura',
                'UP' => 'Uttar Pradesh',
                'UT' => 'Uttarakhand',
                'WB' => 'West Bengal',
            ],
        ],
        'United States' => [
            'currency' => 'USD',
            'symbol' => '$',
            'states' => [
                'AL' => 'Alabama',
                'AK' => 'Alaska',
                'AZ' => 'Arizona',
                'AR' => 'Arkansas',
                'CA' => 'California',
                'CO' => 'Colorado',
                'CT' => 'Connecticut',
                'DE' => 'Delaware',
                'FL' => 'Florida',
                'GA' => 'Georgia',
                'HI' => 'Hawaii',
                'ID' => 'Idaho',
                'IL' => 'Illinois',
                'IN' => 'Indiana',
                'IA' => 'Iowa',
                'KS' => 'Kansas',
                'KY' => 'Kentucky',
                'LA' => 'Louisiana',
                'ME' => 'Maine',
                'MD' => 'Maryland',
                'MA' => 'Massachusetts',
                'MI' => 'Michigan',
                'MN' => 'Minnesota',
                'MS' => 'Mississippi',
                'MO' => 'Missouri',
                'MT' => 'Montana',
                'NE' => 'Nebraska',
                'NV' => 'Nevada',
                'NH' => 'New Hampshire',
                'NJ' => 'New Jersey',
                'NM' => 'New Mexico',
                'NY' => 'New York',
                'NC' => 'North Carolina',
                'ND' => 'North Dakota',
                'OH' => 'Ohio',
                'OK' => 'Oklahoma',
                'OR' => 'Oregon',
                'PA' => 'Pennsylvania',
                'RI' => 'Rhode Island',
                'SC' => 'South Carolina',
                'SD' => 'South Dakota',
                'TN' => 'Tennessee',
                'TX' => 'Texas',
                'UT' => 'Utah',
                'VT' => 'Vermont',
                'VA' => 'Virginia',
                'WA' => 'Washington',
                'WV' => 'West Virginia',
                'WI' => 'Wisconsin',
                'WY' => 'Wyoming',
            ],
        ],
        'United Kingdom' => [
            'currency' => 'GBP',
            'symbol' => '£',
            'states' => [
                'ENG' => 'England',
                'SCT' => 'Scotland',
                'WLS' => 'Wales',
                'NIR' => 'Northern Ireland',
            ],
        ],
        'United Arab Emirates' => [
            'currency' => 'AED',
            'symbol' => 'د.إ',
            'states' => [
                'AZ' => 'Abu Dhabi',
                'AJ' => 'Ajman',
                'DU' => 'Dubai',
                'FU' => 'Fujairah',
                'RK' => 'Ras Al Khaimah',
                'SH' => 'Sharjah',
                'UM' => 'Umm Al Quwain',
            ],
        ],
        'Australia' => [
            'currency' => 'AUD',
            'symbol' => 'A$',
            'states' => [
                'NSW' => 'New South Wales',
                'VIC' => 'Victoria',
                'QLD' => 'Queensland',
                'SA' => 'South Australia',
                'WA' => 'Western Australia',
                'TAS' => 'Tasmania',
                'ACT' => 'Australian Capital Territory',
                'NT' => 'Northern Territory',
            ],
        ],
    ],
];
